server:
  port: 8761                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: 127.0.0.1         # 指定该Eureka实例的主机名,这里最好还是写在host里面好一些
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
